SELECT ID, NAME, HOST_ID
FROM PLACES
WHERE HOST_ID IN (
    SELECT HOST_ID
    FROM PLACES
    GROUP BY HOST_ID
    HAVING COUNT(HOST_ID) > 1
)
ORDER BY ID;

/*
WITH tmp AS (
    SELECT ID, HOST_ID
    FROM PLACES
)

SELECT DISTINCT PLACES.ID, PLACES.NAME, PLACES.HOST_ID
FROM PLACES JOIN tmp
ON PLACES.ID != tmp.ID AND PLACES.HOST_ID = tmp.HOST_ID
ORDER BY PLACES.ID;
*?